# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dateTime',
            new_name='post_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
